import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: '#12151D' },
  shade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(8, 12, 20, 0.8)' },
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 30 },
  eyebrow: { alignSelf: 'center', color: '#D5B87F', fontSize: 11, letterSpacing: 4, fontWeight: '700' },
  title: { alignSelf: 'center', color: '#FFF5E3', fontSize: 30, fontWeight: '800', marginTop: 10 },
  subtitle: { alignSelf: 'center', color: '#CCC8C0', fontSize: 14, marginTop: 9 },
  summary: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', backgroundColor: 'rgba(25, 36, 50, 0.94)', borderWidth: 1, borderColor: '#3A4655', borderRadius: 15, paddingVertical: 15, marginTop: 22 },
  summaryLabel: { color: '#93A0B1', fontSize: 11, textAlign: 'center' },
  summaryValue: { color: '#F1DEC0', fontSize: 17, fontWeight: '800', textAlign: 'center', marginTop: 5 },
  divider: { width: 1, height: 32, backgroundColor: '#3A4655' },
  list: { paddingTop: 18, paddingBottom: 36 },
  row: { gap: 12, marginBottom: 12, justifyContent: 'center' },
  cardItem: {
    flexGrow: 0,
    backgroundColor: 'rgba(25, 36, 50, 0.96)',
    borderWidth: 2,
    borderRadius: 15,
    padding: 10,
    overflow: 'visible',
  },
  twoColumnCard: { width: '48%' },
  threeColumnCard: { width: '30.5%' },
  rarityBadge: { position: 'absolute', top: 9, right: 9, zIndex: 2, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  rarityText: { color: '#20242B', fontSize: 9, fontWeight: '800' },
  imageWrap: { width: '100%', aspectRatio: 512 / 720, marginBottom: 10 },
  cardImage: { width: '100%', height: '100%' },
  levelBadge: { position: 'absolute', left: 7, bottom: 7, backgroundColor: 'rgba(8, 12, 20, 0.84)', borderColor: '#EAC681', borderWidth: 1, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  levelText: { color: '#F5D390', fontSize: 11, fontWeight: '800' },
  cardName: { color: '#F5F1E9', fontSize: 14, fontWeight: '700' },
  elementText: { color: '#AAB6C5', fontSize: 11, marginTop: 5, marginBottom: 2 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loading: { color: '#AAB6C5', fontSize: 13 },
  emptyTitle: { color: '#F5F1E9', fontSize: 17, fontWeight: '700' },
});
