import { StyleSheet } from 'react-native';

/** 교환소의 가로형 카드 크기에 맞춘 외부 오라 값입니다. */
export const exchangeCardAura = {
  regular: {
    uniformShadow: true,
    wideBlurRadius: 11.2,
    coreBlurRadius: 5.6,
    wideElevation: 7,
    coreElevation: 4.2,
    spreadScale: 1.0056,
    wideOpacity: 0.77,
    coreOpacity: 0.49,
  },
  maxLevel: {
    uniformShadow: true,
    wideBlurRadius: 16.8,
    coreBlurRadius: 8.4,
    wideElevation: 11.2,
    coreElevation: 7,
    spreadScale: 1.0112,
    wideOpacity: 1,
    coreOpacity: 0.77,
  },
} as const;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#101722' },
  content: { padding: 22, paddingBottom: 44, gap: 14 },
  eyebrow: { color: '#92B9CB', fontSize: 10, letterSpacing: 2 },
  title: { color: '#F5F7FA', fontSize: 28, fontWeight: '800' },
  subtitle: { color: '#B3BECD', fontSize: 14 },
  notice: { backgroundColor: '#20303D', borderRadius: 10, padding: 12 },
  noticeText: { color: '#B6D3E3', fontSize: 12, lineHeight: 18 },
  tabs: { flexDirection: 'row', padding: 5, backgroundColor: '#1B2533', borderRadius: 14, marginVertical: 8 },
  tab: { flex: 1, paddingVertical: 14, alignItems: 'center', borderRadius: 10 },
  activeTab: { backgroundColor: '#D7BB7B' },
  tabText: { color: '#9EAEC1', fontWeight: '700', fontSize: 14 },
  activeTabText: { color: '#242015' },
  cardExchangeBanner: { width: '100%' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectionControls: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  selectAllButton: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 34, paddingHorizontal: 9, borderRadius: 9, borderWidth: 1, borderColor: '#7A6744', backgroundColor: '#2C2A25' },
  selectAllText: { color: '#F4D391', fontSize: 12, fontWeight: '700' },
  heading: { color: '#F1F5F9', fontSize: 18, fontWeight: '700' },
  muted: { color: '#A3B1C3', fontSize: 13, lineHeight: 20 },
  cardRow: { flexDirection: 'row', gap: 16, padding: 14, backgroundColor: '#1A2432', borderWidth: 1, borderRadius: 15, alignItems: 'center', overflow: 'visible' },
  cardAuraMask: { position: 'absolute', top: 1, right: 1, bottom: 1, left: 1, borderRadius: 14, backgroundColor: '#1A2432' },
  selectedCard: { backgroundColor: '#29303A' },
  imageWrap: { width: 64, height: 90, position: 'relative' },
  cardImage: { width: '100%', height: '100%', resizeMode: 'contain' },
  rarityBadge: { position: 'absolute', top: 2, right: 2, paddingHorizontal: 2, paddingVertical: 1, borderRadius: 3 },
  rarityText: { color: '#20242B', fontSize: 6, fontWeight: '800' },
  levelBadge: { position: 'absolute', left: 2, bottom: 2, backgroundColor: 'rgba(8, 12, 20, 0.84)', borderColor: '#EAC681', borderWidth: 0.5, borderRadius: 3, paddingHorizontal: 2, paddingVertical: 1 },
  level: { color: '#F5D390', fontSize: 6, fontWeight: '800' },
  cardInfo: { flex: 1, gap: 5 },
  cardName: { color: '#F1F5F9', fontWeight: '700', fontSize: 15 },
  cardValue: { color: '#9DDCEC', fontSize: 15, fontWeight: '700' },
  checkbox: { width: 26, height: 26, borderRadius: 8, borderWidth: 1, borderColor: '#617187', alignItems: 'center', justifyContent: 'center' },
  checked: { backgroundColor: '#D7BB7B', borderColor: '#D7BB7B' },
  checkText: { color: '#242015', fontSize: 17, fontWeight: '800' },
  summary: { backgroundColor: '#1B3040', borderRadius: 16, padding: 22, gap: 10, marginTop: 6 },
  total: { color: '#B5E9F5', fontSize: 30, fontWeight: '800' },
  unit: { color: '#B7C9D9', fontSize: 15 },
  summaryNote: { color: '#A7BCCB', fontSize: 12, lineHeight: 18 },
  button: { backgroundColor: '#D7BB7B', borderRadius: 14, padding: 18, alignItems: 'center', marginTop: 6 },
  buttonText: { color: '#242015', fontSize: 16, fontWeight: '800' },
  disabled: { opacity: 0.35 },
  valueTable: { backgroundColor: '#1A2432', padding: 16, borderRadius: 15, marginTop: 12, gap: 12 },
  tableRow: { flexDirection: 'row', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#2A3648' },
  tableGrade: { flex: 1, color: '#C6D0DD', fontSize: 12 },
  tableNumber: { flex: 1, color: '#C6D0DD', fontSize: 12, textAlign: 'right' },
  tableNote: { color: '#889BB0', fontSize: 11 },
  rateCard: { backgroundColor: '#1A2432', padding: 20, borderRadius: 15, gap: 10, marginBottom: 10 },
  rate: { color: '#D7BB7B', fontSize: 21, fontWeight: '700' },
  inputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1A2432', borderWidth: 1, borderColor: '#53697F', borderRadius: 12, paddingHorizontal: 16 },
  input: { flex: 1, color: '#FFF', fontSize: 22, paddingVertical: 16 },
  presets: { flexDirection: 'row', gap: 8 },
  preset: { flex: 1, backgroundColor: '#253346', paddingVertical: 12, alignItems: 'center', borderRadius: 9 },
  presetText: { color: '#C2D2E3', fontSize: 12 },
  error: { color: '#FDA4AF', fontSize: 13 },
  resultBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(5, 9, 15, 0.82)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  resultDialog: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#182330',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#D7BB7B',
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.45,
    shadowRadius: 24,
    elevation: 16,
  },
  resultIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#D7BB7B',
    backgroundColor: '#2B2A28',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  resultIconText: { color: '#F4D391', fontSize: 27, fontWeight: '800' },
  resultEyebrow: {
    color: '#D5B87F',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2.2,
  },
  resultTitle: {
    color: '#FFF5E3',
    fontSize: 25,
    fontWeight: '800',
    marginTop: 7,
  },
  resultMessage: {
    color: '#AAB6C5',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    marginTop: 10,
  },
  resultReward: {
    width: '100%',
    backgroundColor: '#101722',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#344153',
    paddingVertical: 16,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginTop: 22,
  },
  resultRewardLabel: { color: '#92A1B3', fontSize: 11, fontWeight: '700' },
  resultRewardValue: {
    color: '#B5E9F5',
    fontSize: 27,
    fontWeight: '800',
    marginTop: 5,
  },
  resultButton: {
    width: '100%',
    backgroundColor: '#D7BB7B',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 16,
  },
  resultButtonText: { color: '#242015', fontSize: 16, fontWeight: '800' },
});
