import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: '#12151D' },
  shade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 12, 20, 0.78)',
  },
  content: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 30,
    paddingBottom: 32,
  },
  eyebrow: {
    color: '#D5B87F',
    fontSize: 11,
    letterSpacing: 4,
    fontWeight: '700',
  },
  title: {
    color: '#FFF5E3',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 10,
  },
  subtitle: { color: '#CCC8C0', fontSize: 14, marginTop: 10 },
  previewNote: { color: '#A7AFBA', fontSize: 11, marginTop: 12 },
  stage: {
    flex: 1,
    minHeight: 390,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
  },
  strikeScene: {
    width: 245,
    minHeight: 264,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  heroAuraFrame: {
    width: 171,
    aspectRatio: 512 / 720,
    borderRadius: 17,
    borderWidth: 2,
    backgroundColor: '#151C2C',
    shadowOpacity: 0.88,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 0 },
    elevation: 16,
    overflow: 'visible',
  },
  cardFrame: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#151C2C',
  },
  failedCardFrame: { backgroundColor: '#686D76' },
  heroCard: { width: '100%', height: '100%' },
  failedImageGrayscale: {
    filter: 'grayscale(1)',
    opacity: 0.62,
  },
  failedImageIos: { opacity: 0.28 },
  failedShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(92, 98, 108, 0.48)',
  },
  gradeBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9,
  },
  gradeText: {
    color: '#20242B',
    fontSize: 11,
    fontWeight: '800',
  },
  heroLevelBadge: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    backgroundColor: 'rgba(8, 12, 20, 0.86)',
    borderColor: '#EAC681',
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  heroLevelText: {
    color: '#F5D390',
    fontSize: 15,
    fontWeight: '800',
  },
  strikeOverlay: {
    position: 'absolute',
    top: -10,
    right: -10,
    bottom: -10,
    left: -10,
    zIndex: 100,
    overflow: 'hidden',
    backgroundColor: '#080A0D',
  },
  strikeBackdrop: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.46,
    transform: [{ scale: 1.18 }],
  },
  strikeBackdropShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5, 7, 10, 0.67)',
  },
  forgeVignette: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 34,
    borderColor: 'rgba(0, 0, 0, 0.38)',
  },
  forgeHeader: {
    position: 'absolute',
    top: 54,
    right: 24,
    left: 24,
    alignItems: 'center',
    zIndex: 10,
  },
  forgeCaption: {
    color: '#D5B87F',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 4.5,
  },
  forgeTitle: {
    color: '#FFF2D6',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 8,
    textShadowColor: 'rgba(255, 126, 48, 0.55)',
    textShadowRadius: 12,
    textShadowOffset: { width: 0, height: 0 },
  },
  fullForgeScene: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  furnaceGlow: {
    position: 'absolute',
    top: '45%',
    width: 310,
    height: 180,
    borderRadius: 155,
    backgroundColor: 'rgba(255, 80, 24, 0.17)',
    transform: [{ scaleX: 1.15 }],
  },
  emberField: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  ember: {
    position: 'absolute',
    color: '#FFB052',
    textShadowColor: '#FF542B',
    textShadowRadius: 10,
    fontWeight: '900',
  },
  emberOne: { top: '35%', left: '21%', fontSize: 22, transform: [{ rotate: '18deg' }] },
  emberTwo: { top: '43%', right: '20%', fontSize: 30 },
  emberThree: { top: '54%', left: '16%', fontSize: 15, transform: [{ rotate: '-20deg' }] },
  emberFour: { top: '31%', right: '29%', fontSize: 20 },
  fullHammer: {
    position: 'absolute',
    top: '24%',
    right: '22%',
    alignItems: 'center',
    zIndex: 8,
  },
  fullHammerImage: {
    width: 168,
    height: 168,
  },
  hammerHandle: {
    position: 'absolute',
    top: 0,
    width: 22,
    height: 168,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#4A2818',
    backgroundColor: '#8B4B2C',
    overflow: 'hidden',
  },
  handleHighlight: {
    position: 'absolute',
    top: 3,
    bottom: 3,
    left: 4,
    width: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 196, 125, 0.38)',
  },
  handleGrip: {
    position: 'absolute',
    right: -3,
    left: -3,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#3A2118',
    transform: [{ rotate: '-8deg' }],
  },
  handleGripOne: { top: 36 },
  handleGripTwo: { top: 78 },
  handleGripThree: { top: 120 },
  hammerNeck: {
    position: 'absolute',
    bottom: 43,
    width: 35,
    height: 28,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#222831',
    backgroundColor: '#4C555F',
    zIndex: 2,
  },
  hammerHead: {
    position: 'absolute',
    bottom: 7,
    width: 122,
    height: 52,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#1F252C',
    backgroundColor: '#535E69',
    overflow: 'visible',
    shadowColor: '#000',
    shadowOpacity: 0.75,
    shadowRadius: 10,
    shadowOffset: { width: 6, height: 8 },
    elevation: 12,
    zIndex: 3,
  },
  hammerHeadHighlight: {
    position: 'absolute',
    top: 5,
    right: 9,
    left: 9,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(225, 235, 241, 0.42)',
  },
  hammerHeadBand: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 43,
    width: 30,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: '#77838E',
    backgroundColor: 'rgba(19, 25, 31, 0.18)',
  },
  hammerFace: {
    position: 'absolute',
    right: -12,
    top: 8,
    width: 17,
    height: 34,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#303840',
    backgroundColor: '#6E7B86',
  },
  anvil: {
    position: 'absolute',
    top: '51%',
    width: 280,
    height: 205,
    alignItems: 'center',
    zIndex: 5,
  },
  anvilWrap: {
    position: 'absolute',
    top: '50%',
    width: 266,
    height: 172,
    alignItems: 'center',
    zIndex: 5,
  },
  anvilImage: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.9,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  anvilGlow: {
    position: 'absolute',
    top: -38,
    width: 270,
    height: 100,
    borderRadius: 135,
    backgroundColor: 'rgba(255, 91, 35, 0.2)',
  },
  anvilTop: {
    width: 238,
    height: 42,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#8E99A3',
    backgroundColor: '#4E5862',
    shadowColor: '#000',
    shadowOpacity: 0.9,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 11 },
    elevation: 15,
    zIndex: 5,
  },
  anvilHorn: {
    position: 'absolute',
    top: 5,
    left: -29,
    width: 56,
    height: 29,
    borderTopLeftRadius: 22,
    borderBottomLeftRadius: 5,
    backgroundColor: '#56616B',
    transform: [{ skewX: '-22deg' }],
  },
  anvilTopHighlight: {
    position: 'absolute',
    top: 3,
    right: 8,
    left: 8,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(224, 234, 240, 0.38)',
  },
  heatedMetal: {
    position: 'absolute',
    top: 32,
    left: 90,
    width: 86,
    height: 9,
    borderRadius: 8,
    backgroundColor: '#FF5A2A',
    shadowColor: '#FF3A20',
    shadowOpacity: 1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 18,
    zIndex: 8,
    overflow: 'hidden',
  },
  heatedMetalCore: {
    position: 'absolute',
    top: 3,
    right: 8,
    left: 8,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#FFF0A6',
  },
  anvilShoulder: {
    width: 150,
    height: 24,
    backgroundColor: '#3F4851',
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderColor: '#272E35',
  },
  anvilStem: {
    width: 92,
    height: 82,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderColor: '#292F36',
    backgroundColor: '#414A53',
    overflow: 'hidden',
  },
  anvilStemHighlight: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 10,
    width: 12,
    backgroundColor: 'rgba(171, 184, 194, 0.16)',
  },
  anvilBase: {
    width: 188,
    height: 31,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#626E78',
    backgroundColor: '#343B43',
    overflow: 'hidden',
  },
  anvilBaseHighlight: {
    position: 'absolute',
    top: 3,
    right: 7,
    left: 7,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(198, 210, 219, 0.24)',
  },
  fullImpact: {
    position: 'absolute',
    top: '42%',
    width: 240,
    height: 180,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 12,
  },
  impactRingOuter: {
    position: 'absolute',
    width: 180,
    height: 90,
    borderRadius: 90,
    borderWidth: 3,
    borderColor: 'rgba(255, 126, 49, 0.56)',
    backgroundColor: 'rgba(255, 91, 35, 0.1)',
  },
  impactRingInner: {
    position: 'absolute',
    width: 112,
    height: 54,
    borderRadius: 56,
    borderWidth: 2,
    borderColor: '#FFE6A3',
    backgroundColor: 'rgba(255, 222, 130, 0.14)',
  },
  sparkText: {
    position: 'absolute',
    top: 19,
    color: '#FFF2B0',
    fontSize: 42,
    letterSpacing: 10,
    textShadowColor: '#FF6A28',
    textShadowRadius: 20,
  },
  bangText: {
    color: '#FFF7DB',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: 4,
    textShadowColor: '#FF4F24',
    textShadowRadius: 15,
  },
  strikeStatus: {
    position: 'absolute',
    right: 24,
    bottom: 126,
    left: 24,
    height: 50,
    borderRadius: 15,
    backgroundColor: 'rgba(13, 17, 22, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(213, 184, 127, 0.35)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    zIndex: 15,
  },
  strikeProgress: {
    color: '#F4E6CC',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  strikeDots: {
    flexDirection: 'row',
    gap: 6,
  },
  strikeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4B5563',
  },
  strikeDotActive: {
    width: 20,
    backgroundColor: '#F0C674',
    shadowColor: '#FF8A3D',
    shadowOpacity: 0.9,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  },
  strikeCount: {
    minWidth: 32,
    color: '#D5B87F',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  strikeBanner: {
    position: 'absolute',
    right: 24,
    bottom: 20,
    left: 24,
    zIndex: 8,
  },
  emptyCard: {
    width: 171,
    height: 240,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#9E895E',
    borderRadius: 12,
    backgroundColor: '#192432',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  emptyIcon: { color: '#EAC681', fontSize: 48 },
  emptyText: { color: '#DCCDB0', textAlign: 'center', lineHeight: 24 },
  stageText: {
    color: '#E4D9C4',
    fontSize: 14,
    marginTop: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  resultTitle: {
    color: '#F5D390',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 18,
  },
  failure: { color: '#EDAB9F' },
  actions: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
    marginTop: 22,
  },
  hint: {
    color: '#C6C6CB',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 18,
  },
  error: {
    color: '#F1C6AD',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 20,
  },
  button: {
    backgroundColor: '#EAC681',
    minHeight: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  buttonText: { color: '#292015', fontSize: 18, fontWeight: '800' },
  disabled: { opacity: 0.4 },
});
