import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#101722' },
  accessStatusScreen: { flex: 1, backgroundColor: '#101722', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  accessStatusMark: { color: '#D5B87F', fontSize: 28, marginBottom: 16 },
  accessStatusTitle: { color: '#FFF5E3', fontSize: 20, fontWeight: '800', textAlign: 'center' },
  content: { paddingHorizontal: 20, paddingTop: 32, paddingBottom: 42 },
  eyebrow: { color: '#D5B87F', fontSize: 11, letterSpacing: 4, fontWeight: '700' },
  welcome: { color: '#FFF5E3', fontSize: 26, fontWeight: '800', marginTop: 12 },
  subtitle: { color: '#AAB6C5', fontSize: 14, marginTop: 8 },
  playerCard: { height: 210, borderRadius: 22, backgroundColor: '#192432', borderWidth: 1, borderColor: '#3A4655', marginTop: 24, overflow: 'hidden', flexDirection: 'row' },
  glowLarge: { position: 'absolute', width: 250, height: 250, borderRadius: 125, backgroundColor: '#26384B', left: -80, top: -100 },
  glowSmall: { position: 'absolute', width: 130, height: 130, borderRadius: 65, backgroundColor: '#313443', left: 100, bottom: -80 },
  playerInfo: { flex: 1, padding: 20, justifyContent: 'center', zIndex: 2 },
  profileLabel: { color: '#D5B87F', fontSize: 9, letterSpacing: 2, fontWeight: '700' },
  nickname: { color: '#FFF', fontSize: 25, fontWeight: '800', marginTop: 8 },
  levelText: { color: '#B0BBC9', fontSize: 12, marginTop: 4 },
  currencyCard: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: 9, backgroundColor: 'rgba(234,198,129,0.1)', borderWidth: 1, borderColor: 'rgba(234,198,129,0.35)', borderRadius: 11, paddingHorizontal: 12, paddingVertical: 8, marginTop: 17 },
  crystalIcon: { color: '#9DDCEC', fontSize: 17 },
  currencyLabel: { color: '#AAB6C5', fontSize: 9 },
  currencyValue: { color: '#F5F1E9', fontSize: 14, fontWeight: '800', marginTop: 1 },
  characterWrap: { width: '42%', height: '100%' },
  character: { width: '100%', height: '100%' },
  characterShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(16,23,34,0.15)' },
  stars: { position: 'absolute', left: 0, right: 0, bottom: 0, alignItems: 'center', paddingVertical: 7, backgroundColor: 'rgba(8,12,20,0.72)' },
  starText: { color: '#EAC681', fontSize: 10, letterSpacing: 2 },
  grid: { gap: 11, marginTop: 22 },
  menuCard: { minHeight: 82, backgroundColor: '#192432', borderWidth: 1, borderColor: '#344153', borderRadius: 16, padding: 13, flexDirection: 'row', alignItems: 'center' },
  iconWrap: { width: 54, height: 54, borderRadius: 15, borderWidth: 1, backgroundColor: '#111B28', alignItems: 'center', justifyContent: 'center' },
  icon: { width: 31, height: 31 },
  menuCopy: { flex: 1, marginLeft: 14 },
  menuTitle: { color: '#F5F1E9', fontSize: 16, fontWeight: '700' },
  menuDescription: { color: '#929FAF', fontSize: 12, marginTop: 5 },
  arrow: { fontSize: 29, marginHorizontal: 6 },
  guideCard: { flexDirection: 'row', backgroundColor: '#1B3040', borderRadius: 16, padding: 17, marginTop: 20, alignItems: 'center', gap: 14 },
  guideMark: { color: '#EAC681', fontSize: 26 },
  guideCopy: { flex: 1 },
  guideTitle: { color: '#E9EEF4', fontSize: 14, fontWeight: '700' },
  guideText: { color: '#A7BCCB', fontSize: 11, lineHeight: 17, marginTop: 5 },
  debugButton: { marginTop: 16, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: '#44536A', alignItems: 'center', backgroundColor: '#151D29' },
  debugButtonText: { color: '#B9C4D3', fontSize: 12, fontWeight: '600' },
});
